### ISSUE TITLE
Add legal boilerplate

### ISSUE THREAD

**Issue by mickdekkers** [eve-apps/karma#1]
These are the things that we need to add to Karma so we don't get sued.
## TODO
- [ ] EU Cookie notice
  - We can use [cookieconsent2](https://github.com/silktide/cookieconsent2) for this
- [ ] Privacy Policy
  - This is also required for the cookie notice
  - [ ] Generate a Privacy Policy document
  - [ ] Figure out how to handle changes to the Privacy Policy
- [ ] Terms of Service
  - [ ] Generate a Terms of Service document
  - [ ] Figure out how to handle changes to the TOS
- [ ] [CCP Copyright notice](https://wiki.eveonline.com/en/wiki/Fansites_guidelines)
  - Add to the footer on every page
